// Exact expected-value AI for Cubilete. Pure: no DOM, no randomness.
// Hands are multisets of 5 dice over 6 faces (252 states); holds are sub-multisets (462 total).
import { evaluate, compare, scoreFor } from './rules.js';

let T = null;

function multisets(k) {
  const out = [];
  (function rec(i, left, cur) {
    if (i === 5) { cur[5] = left; out.push(cur.slice()); return; }
    for (let c = 0; c <= left; c++) { cur[i] = c; rec(i + 1, left - c, cur); }
  })(0, k, [0, 0, 0, 0, 0, 0]);
  return out;
}
const key = (v) => v.join('');

function ensureTables() {
  if (T) return T;
  const fact = [1, 1, 2, 6, 24, 120];
  const hands = multisets(5);
  const handIdx = new Map(hands.map((h, i) => [key(h), i]));
  const subs = [];
  const subIdx = new Map();
  for (let k = 0; k <= 5; k++) for (const m of multisets(k)) { subIdx.set(key(m), subs.length); subs.push(m); }
  const outcomes = [];
  for (let m = 0; m <= 5; m++) {
    outcomes[m] = multisets(m).map((o) => {
      let denom = 1;
      for (const c of o) denom *= fact[c];
      return { o, p: fact[m] / denom / Math.pow(6, m) };
    });
  }
  const subNext = [];
  const subProb = [];
  subs.forEach((sub, si) => {
    const m = 5 - sub.reduce((a, b) => a + b, 0);
    const nx = [];
    const pr = [];
    for (const { o, p } of outcomes[m]) {
      nx.push(handIdx.get(key(sub.map((c, f) => c + o[f]))));
      pr.push(p);
    }
    subNext[si] = Uint8Array.from(nx);
    subProb[si] = Float64Array.from(pr);
  });
  const handSubs = hands.map((h) => {
    const list = [];
    (function rec(f, cur) {
      if (f === 6) { list.push(subIdx.get(key(cur))); return; }
      for (let c = 0; c <= h[f]; c++) { cur[f] = c; rec(f + 1, cur); }
    })(0, [0, 0, 0, 0, 0, 0]);
    return list;
  });
  const handEval = hands.map((h) => {
    const dice = [];
    h.forEach((c, f) => { for (let i = 0; i < c; i++) dice.push(f + 1); });
    return evaluate(dice);
  });
  T = { hands, handIdx, subs, subNext, subProb, handSubs, handEval, fullRollSub: subIdx.get('000000') };
  return T;
}

function idxOfDice(dice) {
  const v = [0, 0, 0, 0, 0, 0];
  for (const d of dice) v[d - 1]++;
  return T.handIdx.get(key(v));
}

function expectRoll(si, Vnext) {
  const nx = T.subNext[si];
  const pr = T.subProb[si];
  let e = 0;
  for (let k = 0; k < nx.length; k++) e += pr[k] * Vnext[nx[k]];
  return e;
}

/**
 * Backward induction. stopValue(handIdx, rollsUsed) is the value of stopping now.
 * Returns V[u] (Float64Array over 252 hands) for u = uFrom..uMax. Five-of-a-kind is terminal.
 */
function solve(stopValue, uFrom, uMax, rollFactor = 1) {
  const N = T.hands.length;
  const V = [];
  V[uMax] = new Float64Array(N);
  for (let h = 0; h < N; h++) V[uMax][h] = stopValue(h, uMax);
  for (let u = uMax - 1; u >= uFrom; u--) {
    const cur = new Float64Array(N);
    const next = V[u + 1];
    for (let h = 0; h < N; h++) {
      let best = stopValue(h, u);
      if (T.handEval[h].count < 5) {
        for (const si of T.handSubs[h]) {
          const e = expectRoll(si, next) * rollFactor;
          if (e > best) best = e;
        }
      }
      cur[h] = best;
    }
    V[u] = cur;
  }
  return V;
}

const classKey = (hand) => `${hand.count}${hand.face}`;

/**
 * P_BEAT[cap][class]: probability that one opponent with `cap` rolls, playing to maximise
 * P(final hand strictly beats target), does beat a target of that (count, face) class.
 * Generated by tools/gen_pbeat.js; tests assert it matches computePBeat().
 */
export const P_BEAT = /*P_BEAT_START*/{"1":{"15":0.984568,"21":0.953704,"22":0.911265,"23":0.857253,"24":0.776235,"25":0.637346,"31":0.570473,"32":0.499743,"33":0.417438,"34":0.315844,"35":0.187243,"41":0.158951,"42":0.128086,"43":0.09465,"44":0.058642,"45":0.020062},"2":{"15":0.999762,"21":0.997857,"22":0.993016,"23":0.983452,"24":0.961801,"25":0.912242,"31":0.886192,"32":0.848543,"33":0.799034,"34":0.711871,"35":0.553787,"41":0.51138,"42":0.455711,"43":0.395255,"44":0.299864,"45":0.147781},"3":{"15":0.999996,"21":0.999901,"22":0.99945,"23":0.99814,"24":0.993797,"25":0.977146,"31":0.970778,"32":0.958242,"33":0.938213,"34":0.898398,"35":0.782973,"41":0.757214,"42":0.715223,"43":0.665423,"44":0.568278,"45":0.333229}}/*P_BEAT_END*/;

export function computePBeat() {
  ensureTables();
  const classes = new Map();
  T.handEval.forEach((h) => { if (h.count < 5) classes.set(classKey(h), h); });
  const table = {};
  for (let cap = 1; cap <= 3; cap++) {
    table[cap] = {};
    for (const [k, target] of classes) {
      const sv = (hi) => (compare(T.handEval[hi], target) > 0 ? 1 : 0);
      const V = solve(sv, 1, cap);
      table[cap][k] = Math.round(expectRoll(T.fullRollSub, V[1]) * 1e6) / 1e6;
    }
  }
  return table;
}

let pbeatCache = null;
function pBeat(cap, hand) {
  const tbl = P_BEAT || (pbeatCache ||= computePBeat());
  return tbl[Math.min(3, Math.max(1, cap))][classKey(hand)] ?? 0;
}

/**
 * Decide what to do after a roll.
 * opts.style: 'cool' (exact) | 'gambler' (overvalues carabinas) | 'cautious' (discounts rolling on)
 * opts.level: 'sharp' (best option) | 'casual' (a random option within 80% of the best)
 * @returns {{hold: boolean[], stop: boolean}}
 */
export function decide({ dice, held, rollsUsed, maxRolls, isOpener, bestOnTable, opponentsAfter, rollCap }, opts = {}, rand = Math.random) {
  ensureTables();
  const style = opts.style || 'cool';
  const level = opts.level || 'sharp';
  const carabinaBias = style === 'gambler' ? 1.6 : 1;
  const rollFactor = style === 'cautious' ? 0.9 : 1;
  const h = idxOfDice(dice);
  const hand = T.handEval[h];
  if (hand.count === 5 || rollsUsed >= maxRolls) return { hold: held.slice(), stop: true };

  const stopValue = (hi, u) => {
    const hd = T.handEval[hi];
    let v = scoreFor(hd);
    if (hd.count === 5) return v * carabinaBias; // round ends on the spot
    if (!isOpener && bestOnTable) {
      const c = compare(hd, bestOnTable);
      v *= c > 0 ? 1 : c === 0 ? 0.5 : 0;
    }
    if (opponentsAfter > 0) {
      const cap = isOpener ? u : rollCap;
      v *= Math.pow(1 - pBeat(cap, hd), opponentsAfter);
    }
    return v;
  };

  const V = solve(stopValue, rollsUsed + 1, maxRolls, rollFactor);
  const options = [{ sub: -1, value: stopValue(h, rollsUsed) }];
  for (const si of T.handSubs[h]) {
    if (T.subNext[si].length === 1) continue; // holding everything == stopping
    options.push({ sub: si, value: expectRoll(si, V[rollsUsed + 1]) * rollFactor });
  }
  let pick = options[0];
  for (const o of options) if (o.value > pick.value + 1e-9) pick = o;
  if (level === 'casual') {
    // anything within 70% of the best play, and never fewer than the two best options
    const sorted = options.slice().sort((a, b) => b.value - a.value);
    let pool = sorted.filter((o) => o.value >= sorted[0].value * 0.7);
    if (pool.length < 2) pool = sorted.slice(0, 2);
    pick = pool[Math.min(pool.length - 1, Math.floor(rand() * pool.length))];
  }
  if (pick.sub < 0) return { hold: held.slice(), stop: true };

  const need = T.subs[pick.sub].slice();
  const hold = [false, false, false, false, false];
  const order = [...dice.keys()].sort((a, b) => Number(held[b]) - Number(held[a]) || a - b);
  for (const i of order) {
    const f = dice[i] - 1;
    if (need[f] > 0) { hold[i] = true; need[f]--; }
  }
  return { hold, stop: false };
}

/** Expected patas of stopping vs rolling — exposed for tests/debug. */
export function _tables() { return ensureTables(); }
